### PR TITLE
Arithmoi fails to build on GHC 7.10.2 due to Word64 not being imported.

### PR DESCRIPTION
**Pull request by tebello-thejane**
Attempt to fix the following error when compiling on GHC 7.10.2:

```
    Not in scope: type constructor or class ‘Word64’
    Perhaps you meant ‘Word’ (imported from Prelude)
```

### CODE REVIEW

**Comment by cartazio** [comment]
Thanks. I'll get on this soon. I've accumulated a bit of a backlog here :)

**Comment by Bodigrim** [comment]
@tebello-thejane your fix causes warning `The import of ‘Data.Word’ is redundant` on 64bit architecture. Could you please wrap import into `#if WORD_SIZE_IN_BITS == 32 ... #endif`?
