### PR TITLE
GHC 7.10.2 was released a few days ago

### PR DESCRIPTION
**Pull request by tebello-thejane**
Yes, I know that the build will fail with the error below. But that's the whole point of CI.

```
Math/NumberTheory/Moduli.hs:246:11:
    Not in scope: type constructor or class ‘Word64’
    Perhaps you meant ‘Word’ (imported from Prelude)
```

### CODE REVIEW

**Comment by tebello-thejane** [comment]
Hmm.. The travis build succeeds? This is surprising.

On my system it fails to build on 7.10.2 (via ``cabal`` and via ``stack`` LTS-3.0) with
```
Math/NumberTheory/Moduli.hs:246:11:
    Not in scope: type constructor or class ‘Word64’
    Perhaps you meant ‘Word’ (imported from Prelude)
```

I will create a pull request to fix this shortly...

**Comment by Bodigrim** [comment]
Travis build succeeds, because it is 64bit. And the only usage of `Word64` in `Math.NumberTheory.Moduli` is guarded by `#if WORD_SIZE_IN_BITS == 32`. Let us continue this discussion in #10.

Sorry, I have already updated `.travis.yml` to use GHC 7.10.3.
